sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm

install:
  - travis_retry composer install --no-interaction